// Generated by CoffeeScript 1.4.0
(function() {

  describe('FizzBuzz', function() {
    return it('should return the results of the FizzBuzz game from 1 up to the number provided by the user', function() {
      var result;
      result = fizzbuzz(15);
      return expect(result).toEqual([1, 2, "Fizz", 4, "Buzz", "Fizz", 7, 8, "Fizz", "Buzz", 11, "Fizz", 13, 14, "FizzBuzz"]);
    });
  });

}).call(this);
