// Generated by CoffeeScript 1.4.0
(function() {

  this.fizzbuzz = function(max_number) {
    var i, result;
    result = [];
    i = 1;
    while (i < max_number + 1) {
      if ((i % 3 === 0) && (i % 5 === 0)) {
        result.push("FizzBuzz");
      } else if (i % 3 === 0) {
        result.push("Fizz");
      } else if (i % 5 === 0) {
        result.push("Buzz");
      } else {
        result.push(i);
      }
      i++;
    }
    return result;
  };

}).call(this);
